services:
  website:
    image: nginx:alpine
    container_name: website
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./src/public:/usr/share/nginx/html:ro
    ports:
      - 3000:80
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    command: tunnel run --token $CLOUDFLARED_TOKEN
    env_file: .env
    restart: unless-stopped
